require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: ./.rubocop.yml
Style/HashSyntax:
  Enabled: false
Layout/LineLength:
  Exclude:
    - Gemfile
AllCops:
  Exclude:
    - vendor/**/*
Jekyll/NoPutsAllowed:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: slashes
