os: linux
language: ruby
cache: bundler

branches:
  only:
    - release

install:
  - bundle config set without 'development'
  - bundle install

script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination ./site
  - htmlproofer --assume-extension --allow-hash-href --url-ignore "/linkedin/,/digikey/" ./_site

deploy:
  provider: pages
  email: deploy@travis-ci.org
  name: Deployment Bot
  target_branch: master
  local_dir: ./site
  token: $GITHUB_TOKEN
  keep_history: true
  skip_cleanup: true
  on:
    branch: release
    condition: $TRAVIS_EVENT_TYPE != cron

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - emma.sax4@gmail.com
