os: linux
language: ruby
cache: bundler
branches:
  only:
    - release

notifications:
  email: false
  slack:
    rooms:
      - emmasax4:Cyvo08l3YdvxR3hrXizDUsOk
    on_success: always
    on_failure: always
    on_pull_requests: true
    template:
      - "*%{result}* build for `%{repository_slug}`: build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*."
      - "Message: %{message}"

install:
  - bundle install

script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination ./site

after_success:
  - htmlproofer --assume-extension --allow-hash-href --internal-domains "/emmasax4.info/" --url-ignore "/linkedin/,/digikey/" ./site

deploy:
  provider: pages
  email: deploy@travis-ci.org
  name: Deployment Bot
  target_branch: master
  local_dir: ./site
  token: $GITHUB_TOKEN
  keep_history: true
  edge: true
  on:
    branch: release
