os: linux
language: ruby
cache: bundler

branches:
  only:
    - release

# before_install:
#   - export TZ=America/Chicago

install:
  - bundle config set without 'development'
  - bundle install

script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination ./site

jobs:
  include:
    - stage: Test
      name: External Link Check
      script: htmlproofer --assume-extension --url-ignore "/linkedin/,/digikey/" --external-only --internal-domains         "/emmasax4.info/" ./site
    - stage: Test
      name: Internal Link Check
      script: htmlproofer --assume-extension --allow-hash-href --url-ignore "/linkedin/,/digikey/" ./site; exit 0

    - stage: Deploy
      if: (type NOT IN (pull_request)) AND (branch = release)
      deploy:
        provider: pages
        email: deploy@travis-ci.org
        name: Deployment Bot
        target_branch: master
        local_dir: ./site
        token: $GITHUB_TOKEN
        keep_history: true
        skip_cleanup: true


notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - emma.sax4@gmail.com
