os: linux
language: ruby
cache: bundler

branches:
  only:
    - release

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - emma.sax4@gmail.com

# before_install:
#   - export TZ=America/Chicago

install:
  - bundle config set without 'development'
  - bundle install

jobs:
  include:
    - stage: Test
      script:
        - JEKYLL_ENV=production bundle exec jekyll build --destination ./site
        - htmlproofer --assume-extension --url-ignore "/linkedin/,/digikey/" --external-only --internal-domains       "/emmasax4.info/" ./site
        - htmlproofer --assume-extension --allow-hash-href --disable-external ./site; return 0
    - stage: Deploy
      if: (type NOT IN (pull_request)) AND (branch = release)
      script: JEKYLL_ENV=production bundle exec jekyll build --destination ./site
      deploy:
        - provider: pages
          email: deploy@travis-ci.org
          name: Deployment Bot
          target_branch: master
          local_dir: ./site
          token: $GITHUB_TOKEN
          keep_history: true
          skip_cleanup: true
