language: ruby
cache: bundler

branches:
  only:
    - release

install:
  - bundle config set without 'development'
  - bundle install

script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination ./site
  - echo "running changes"
  - git diff
  - echo $(.github/travis_changes.sh)

deploy:
  provider: pages
  local_dir: ./site
  target_branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  cleanup: false
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: release
    condition: $TRAVIS_EVENT_TYPE != cron

notifications:
  email:
    on_success: never
    on_failure: always
