os: linux
language: ruby
cache: bundler
branches:
  only:
    - release

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - emma.sax4@gmail.com

before_install:
  - export TZ=America/Chicago

install:
  - bundle config set without 'development'
  - bundle install

jobs:
  include:
    - stage: Test
      name: Jekyll Build
      script:
        - JEKYLL_ENV=production bundle exec jekyll build --destination ./site
    - stage: Test
      name: HTML Proofer
      before_script:
        - JEKYLL_ENV=production bundle exec jekyll build --destination ./site
      script:
        - htmlproofer --assume-extension --allow-hash-href --internal-domains "/emmasax4.info/" --url-ignore "/linkedin/,/digikey/" ./site

    - stage: Deploy
      name: GitHub Pages
      before_deploy:
        - JEKYLL_ENV=production bundle exec jekyll build --destination ./site
      deploy:
        - provider: pages
          email: deploy@travis-ci.org
          name: Deployment Bot
          target_branch: master
          local_dir: ./site
          token: $GITHUB_TOKEN
          keep_history: true
          skip_cleanup: true
          on:
            branch: release
      if: (type NOT IN (pull_request)) AND (branch = release)
