os: linux
language: ruby
cache: bundler

branches:
  only:
    - release

# before_install:
#   - export TZ=America/Chicago

install:
  - bundle config set without 'development'
  - bundle install

jobs:
  include:
    - stage: Test
      name: Jekyll Build
      script: JEKYLL_ENV=production bundle exec jekyll build --destination ./site
    - stage: Test
      name: External Link Check
      script:
        - JEKYLL_ENV=production bundle exec jekyll build --destination ./site
        - htmlproofer --assume-extension --url-ignore "/linkedin/,/digikey/" --external-only
          --internal-domains "/emmasax4.info/" ./site
    - stage: Test
      name: Internal Link Check
      script:
        - JEKYLL_ENV=production bundle exec jekyll build --destination ./site
        - echo $(htmlproofer --assume-extension --allow-hash-href --url-ignore "/linkedin/,/digikey/" ./site)


    - stage: Deploy
      if: (type NOT IN (pull_request)) AND (branch = release)
      script: JEKYLL_ENV=production bundle exec jekyll build --destination ./site
      deploy:
        provider: pages
        email: deploy@travis-ci.org
        name: Deployment Bot
        target_branch: master
        local_dir: ./site
        token: $GITHUB_TOKEN
        keep_history: true
        skip_cleanup: true


notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - emma.sax4@gmail.com
