os: linux
language: ruby
cache: bundler
branches:
  only:
    - release

notifications:
  email: false
  slack:
    secure: LWMZFRNa/MS8U6lukB6sWod9A8sVY+zsd6V7pC8Gos0no7pkbtApt88eeJU7InRuJ65Lo+rxjWH1T64PdTT+s8vFGoBB6NzJk+E0oxrsm05MvW3aUde6tsX75BCBqVWu5LmTu+M4QRmbiGaMOndBe1y5L3oai6jJzDGpsSiFAN1yFMOx3tbw1p/788DCKr9n4BMq1BqoCaIKLArxEcJ/vH62vyFHrPQQvBQpi24TSsplSASaaLMlLGF3rXQAzBvDY1UpOSiiuMpTuj82O+d2rtN2vqO06qcYQwEU8dycxW5ku+UJRyM6toQTQW6zcwM3Mx+vDWLsABAUwfZKENmUBTGqvGpXDRzvJYV1ZeZqCgDZl/VxI3G2nvWU4fsXdTKE9KJ7fUGqNwSIFilPUB3XVI3I1AP5mQ8Kp5oOoY8tO3xG4weS8PPdwHo3bEnoQeMTg4HHcPXAXcH414QLCctXpL2F8NGxNkCHX3tk6QE0ImjiJe5+7bE97QX2TSDJc1hK6zzUqfBSCUqcT/2dmZwpMWOMolLgy407rn24fKOglry7ZTXCkVSFNHEY+WvIKjvlL3VptFvWO0Q2MnNliHy/42ZUnLJACCbgd56gt8l0da2hdP6OQp2JNvhPOr7cijS3WFVzScMvFFo25DL8mjSMlMGZ2rTRC8Kr5/vM62Bf6G4=
    on_success: always
    on_failure: always
    on_pull_requests: true

script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination ./site

after_success:
  - htmlproofer --assume-extension --allow-hash-href --internal-domains /emmasax4.info/ --url-ignore /linkedin/,/digikey/ ./site

deploy:
  provider: pages
  email: deploy@travis-ci.org
  name: Deployment Bot
  target_branch: master
  local_dir: ./site
  token: $GITHUB_TOKEN
  keep_history: true
  edge: true
  on:
    branch: release
