title: Emma Sax
author: Emma Sax
description: Emma Sax's personal website and blog. Includes information about my social media profiles, résumé, and hobbies.
url: https://emmasax4.info
github_repo: https://github.com/emmasax4/emmasax4.info
future: false
timezone: UTC
highlighter: rouge
jekyll-mentions: https://github.com
markdown: kramdown

webmaster_verifications:
  google: v04az8eo-0UcZrWCJr7SKAvM6hw90qTCBQoKx3PlXCA
  bing: 89B2B19FF966341B78EF64EDADE6DF81
  yandex: c2741887f8c30dd1

disqus:
  shortname: emmasax4

sass:
  style: compressed
  sass_dir: assets/css/

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-mentions
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-time-to-read
  - jekyll-titles-from-headings

# We don't need `_legos` here because we're technically never calling a page for each lego element;
#   we're only calling the `{{ element.content }}` of each element. If we viewed a page of each
#   element individually, we'd need to add `_legos` to this list.
include:
  - _blog_posts
  - _pages

collections:
  - blog_posts
  - legos

feed:
  posts_limit: 5

pagination:
  collection: blog_posts
  enabled: true
  per_page: 5
  limit: 0
  sort_field: date
  sort_reverse: true
  trail:
    before: 1
    after: 1
