title: Emma Sax
author: Emma Sax
description: Emma Sax's personal website and blog. Includes information about my social media profiles, resumé, and hobbies.

author_profiles:
  twitter: https://twitter.com/emma_sax4
  linkedin: https://linkedin.com/in/emmasax4
  github: https://github.com/emmasax4
  gitlab: https://gitlab.com/emmasax4
  instagram: https://instagram.com/emmasax4
  facebook: https://facebook.com/emmasax4
  email: emma.sax4@gmail.com

url: https://emmasax4.com # when running the Jekyll server locally, this becomes the local URL; removing this will break the nav bar URLs
domain: emmasax4.com
github_repo: emmasax4.com

timezone: UTC
jekyll-mentions: https://github.com

markdown: CommonMark
commonmark:
  options:
    - SMART
    - UNSAFE
  extensions:
    - autolink
    - table

webmaster_verifications:
  google: 26aZscaByAlAXZ6gkemzbIXHuOdejckdx2AoZxjIU4c
  bing: 89B2B19FF966341B78EF64EDADE6DF81
  yandex: 8d24108cb36eee89

disqus:
  shortname: emmasax4

sass:
  style: compressed
  sass_dir: assets/css/

plugins:
  - jekyll-commonmark
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-mentions
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tidy
  - jekyll-time-to-read
  - jekyll-titles-from-headings

# Jekyll does not need to include these in the finished built _site.
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Add _blog_posts because we want Jekyll to read each file as its own page. It starts with _
# because it's also a collection that needs to be read below. We don't need to include _lego because
# Jekyll doesn't need to convert each file inside to its own page; we call `{{ element.content }}`
# on each LEGO element instead. If we viewed a page of each element individually, we'd need to
# add _lego to this list and add a permalink to each one.
include:
  - _blog_posts

collections:
  - blog_posts
  - lego

feed:
  posts_limit: 5

redirect_from:
  json: false

pagination:
  collection: blog_posts
  enabled: true
  per_page: 5
  limit: 0
  sort_field: date
  sort_reverse: true
  trail:
    before: 1
    after: 1
