# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Emma Sax's Homepage
repository: emma-sax4/emma-sax4.github.io

future: true

pagination:
  enabled: true
  per_page: 3
  sort_field: 'date'
  sort_reverse: true
  collection: 'thoughts'
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: 'thoughts'
  permalink: '/page/:num/'

sass:
  style: compressed
  load_paths:
    - primer/src/

# Build settings
markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - primer/

plugins:
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jemoji
  - jekyll-github-metadata
  - jekyll-paginate-v2

relative_links:
  enabled:     true
  collections: true

collections:
  thoughts:
    output: true
    permalink: /thoughts/:path/

autopages:
  enabled: true
  collections:
    permalink: /thoughts/
    enabled: true

pagination:
  enabled: true
  per_page: 3
  sort_field: 'date'
  sort_reverse: true
  permalink: /:num/
  trail:
    before: 2
    after: 2

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: ""
      type: thoughts
    values:
      layout: thought
      showtable: true
