# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# "bundle exec jekyll serve". If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Emma's Website and Blog
url: https://emmasax4.info

github:
  repo: https://github.com/emma-sax4/emma-sax4.github.io
  owner: https://github.com/emma-sax4

future: true
markdown: kramdown

kramdown:
  smart_quotes: ["rdquo", "rsquo", "quot", "quot"]

sass:
  style: compressed
  sass_dir: assets/css/_sass
  load_paths:
    - primer/src/

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - primer/
  - vendor/

relative_links:
  enabled: true
  collections: true

collections:
  posts:
    output: true
    permalink: /blog/posts/:path
  post_collections:
    output: true
