# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# "bundle exec jekyll serve". If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Emma Sax
description: Emma's Website and Blog
url: https://emmasax4.info

webmaster_verifications:
  google: v04az8eo-0UcZrWCJr7SKAvM6hw90qTCBQoKx3PlXCA
  bing: 89B2B19FF966341B78EF64EDADE6DF81
  yandex: c2741887f8c30dd1

github:
  repo: https://github.com/emma-sax4/emma-sax4.github.io
  owner: https://github.com/emma-sax4

future: true
markdown: kramdown

kramdown:
  smart_quotes:
    - rdquo
    - rsquo
    - quot
    - quot

sass:
  style: compressed
  sass_dir: assets/css/

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

plugins:
  - jekyll-default-layout
  - jekyll-mentions
  - jekyll-paginate-v2
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

relative_links:
  enabled: true
  collections: true

collections:
  posts:
    output: true
    permalink: /blog/posts/:path/

disqus:
  shortname: emmasax4

jekyll-mentions: https://github.com

pagination:
  enabled: true
  per_page: 5
  limit: 0
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2

feed:
  production:
    title: Emma Sax's Blog
    site_url: https://emmasax4.info
    url: https://emmasax4.info/blog/
    items: 5
  development:
    title: LOCAL Emma's Blog
    site_url: https://127.0.0.1:4000
    url: https://127.0.0.1:4000/blog/
    items: 5
