# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# "bundle exec jekyll serve". If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Emma Sax
description: Emma Sax's personal website and blog. Includes information about my social media profiles, résumé, and hobbies.
url: https://emmasax4.info
github_repo: https://github.com/emma-sax4/emma-sax4.github.io

webmaster_verifications:
  google: v04az8eo-0UcZrWCJr7SKAvM6hw90qTCBQoKx3PlXCA
  bing: 89B2B19FF966341B78EF64EDADE6DF81
  yandex: c2741887f8c30dd1

future: false
timezone: UTC
highlighter: rouge
jekyll-mentions: https://github.com
markdown: kramdown

disqus:
  shortname: emmasax4

sass:
  style: compressed
  sass_dir: assets/css/

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

plugins:
  - jekyll-default-layout
  - jekyll-mentions
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-time-to-read
  - jekyll-titles-from-headings

relative_links:
  enabled: true
  collections: true

collections:
  posts:
    output: true

pagination:
  enabled: true
  per_page: 5
  limit: 0
  sort_field: date
  sort_reverse: true
  trail:
    before: 1
    after: 1

feed:
  production:
    title: Emma Sax's Blog
    url: https://emmasax4.info
    items: 5
  development:
    title: LOCAL Emma's Blog
    url: http://127.0.0.1:4000
    items: 5
