name: Auto-Merge Pull Requests
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    # Add a cron to determine what time you want to auto-merge your pull request(s). Crons are written in UTC:
    # https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule.
    - cron: 0 * * * *

jobs:
  merge-schedule:
    name: Auto-Merge
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
