name: Develop
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Define Run Variables
      run: bash scripts/define_run_variables.sh develop ${{ github.repository }} ${{ github.ref }} ${{ github.run_id }} ${{ github.head_ref }}

    - name: Switch to Current Branch
      run: git checkout ${{ env.BRANCH }}

    - name: Configure System
      run: sudo gem update --system 3.0.8 && sudo gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d " ")

    - name: Configure Gem Cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: bundler-cache-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundler-cache-

    - name: Install Gems
      run: bundle config set path "vendor/bundle" && bundle install

    - name: Jekyll Build
      run: JEKYLL_ENV=production bundle exec jekyll build --destination _site

  test:
    - name: HTML Proofer
      run: bash scripts/html_proofer.sh || echo ""

    - name: Rubocop
      run: bundle exec rubocop

    - name: Markdown Linter
      run: bash scripts/markdown_linter.sh

  notify-slack:
    - name: Notify Slack on Success
      if: success()
      uses: emmasax4/slack-notifier-action@main
      with:
        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
        channel: "#general"
        icon_url: https://i.imgur.com/DGrghtn.png
        username: GitHub Actions
        color: "#23c22e"
        title: ${{ github.repository }}
        title_link: https://github.com/${{ github.repository }}
        author_name: ${{ github.actor }}
        author_icon: https://github.com/${{ github.actor }}.png
        text: >-
          Build <${{ env.BUILD_URL }}|${{ github.run_id }}> on branch `${{ env.BRANCH }}`
          in PR <${{ env.PULL_URL }}|#${{ env.PULL_ID }}> *passed*.

    - name: Notify Slack on Failure
      if: failure()
      uses: emmasax4/slack-notifier-action@main
      with:
        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
        channel: "#general"
        icon_url: https://i.imgur.com/DGrghtn.png
        username: GitHub Actions
        color: "#bd2222"
        title: ${{ github.repository }}
        title_link: https://github.com/${{ github.repository }}
        author_name: ${{ github.actor }}
        author_icon: https://github.com/${{ github.actor }}.png
        text: >-
          Build <${{ env.BUILD_URL }}|${{ github.run_id }}> on branch `${{ env.BRANCH }}`
          in PR <${{ env.PULL_URL }}|#${{ env.PULL_ID }}> *failed*.
