name: Build, Test, and Deploy
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: "30 5 * * *" # Every day at 05:30 UTC => 00:30 CDT / 23:30 CST

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Define Environment Variables
      run: bash scripts/set_workflow_variables.sh ${{ github.event_name }} ${{ github.repository }} ${{ github.run_id }} \
                                                  ${{ github.actor }} ${{ github.ref }} ${{ github.head_ref }}

    - name: Switch to Current Branch
      run: git checkout ${{ env.branch }}

    - name: Configure System
      run: sudo gem update --system 3.0.8 && sudo gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d " ")

    - name: Configure Gem Cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: bundler-cache-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundler-cache-

    - name: Install Gems
      run: bundle config set path "vendor/bundle" && bundle install

    - name: Jekyll Build
      run: JEKYLL_ENV=production bundle exec jekyll build --destination _site

    - name: Upload Jekyll Site Artifact
      uses: actions/upload-artifact@v2
      with:
        name: jekyll-site
        path: _site
        retention-days: 1

    - name: HTML Proofer
      run: bash scripts/html_proofer.sh
      continue-on-error: true

    - name: Rubocop
      run: bundle exec rubocop

    - name: Markdown Linter
      run: bash scripts/markdown_linter.sh

    - name: Notify Slack on Success
      if: success()
      uses: emmasax4/slack-notifier-action@main
      with:
        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
        channel: "#general"
        icon_url: https://i.imgur.com/DGrghtn.png
        username: GitHub Actions
        color: "#23c22e"
        title: ${{ github.repository }}
        title_link: https://github.com/${{ github.repository }}
        author_name: ${{ env.actor_name }}
        author_icon: ${{ env.actor_icon }}
        text: ${{ env.build_message }} *passed*.

    - name: Notify Slack on Failure
      if: failure()
      uses: emmasax4/slack-notifier-action@main
      with:
        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
        channel: "#general"
        icon_url: https://i.imgur.com/DGrghtn.png
        username: GitHub Actions
        color: "#bd2222"
        title: ${{ github.repository }}
        title_link: https://github.com/${{ github.repository }}
        author_name: ${{ env.actor_name }}
        author_icon: ${{ env.actor_icon }}
        text: ${{ env.build_message }} *failed*.

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ build ]
    steps:
    - name: Check Out Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Define Environment Variables
      run: echo "deploy_message=Deploy to GitHub Pages was *skipped*." >> $GITHUB_ENV

    - name: Download Jekyll Site Artifact
      uses: actions/download-artifact@v2
      with:
        name: jekyll-site
        path: _site

    - name: GitHub Pages Deploy
      uses: emmasax4/github-pages-deploy-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: _site
        clean: true
        silent: true
        commit_message: "Deploy to ${{ github.repository }}"
        git_config_email: 41898282+github-actions[bot]@users.noreply.github.com
        git_config_name: github-actions[bot]

    - name: Set Deploy Status Message
      run: bash scripts/set_workflow_deploy_message.sh ${{ env.DEPLOYMENT_STATUS }}

    - name: Notify Slack on Success
      if: success()
      uses: emmasax4/slack-notifier-action@main
      with:
        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
        channel: "#general"
        icon_url: https://i.imgur.com/DGrghtn.png
        username: GitHub Actions
        color: "#23c22e"
        title: ${{ github.repository }}
        title_link: https://github.com/${{ github.repository }}
        author_name: github-actions[bot]
        author_icon: https://i.imgur.com/kUxzV44s.png
        text: ${{ env.deploy_message }}

    - name: Notify Slack on Failure
      if: failure()
      uses: emmasax4/slack-notifier-action@main
      with:
        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
        channel: "#general"
        icon_url: https://i.imgur.com/DGrghtn.png
        username: GitHub Actions
        color: "#bd2222"
        title: ${{ github.repository }}
        title_link: https://github.com/${{ github.repository }}
        author_name: github-actions[bot]
        author_icon: https://i.imgur.com/kUxzV44s.png
        text: ${{ env.deploy_message }}

  clean:
    runs-on: ubuntu-latest
    if: always()
    needs: [ build, deploy ]
    steps:
    - name: Delete Jekyll Site Artifact
      uses: emmasax4/delete-artifact-action@main
      with:
        name: jekyll-site
