name: Merge Scheduler
on:
  pull_request:
    types: [edited]
  schedule:
    # Add a cron to determine what time you want to auto-merge your pull request(s). Crons are written in UTC:
    # https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule.
    - cron: '*/5 * * * *'

jobs:
  merge-scheduler:
    runs-on: ubuntu-latest
    steps:
#       - uses: emma-sax4/merge-schedule-action@emmasax4_experimentation
      - uses: emma-sax4/merge-schedule-action@emmasax4_merge_scheduler
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
