name: Pull Request Merge Scheduler
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  merge-scheduler:
    runs-on: ubuntu-latest
    steps:
    - uses: emma-sax4/merge-schedule-action@emmasax4_merge_scheduler
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
