name: Release
on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Setup: Check Out Code'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Setup: Define Run Variables'
      run: bash scripts/define_run_variables.sh release ${{ github.repository }} ${{ github.ref }} ${{ github.run_id }} ${{ github.actor }}

    - name: 'Setup: Switch to Current Branch'
      run: git checkout ${{ env.BRANCH }}

    - name: 'Setup: Configure System'
      run: sudo gem update --system 3.0.8 && sudo gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d " ")

    - name: 'Setup: Configure Gem Cache'
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: bundler-cache-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundler-cache-

    - name: 'Build: Install Gems'
      run: bundle config set path "vendor/bundle" && bundle install

    - name: 'Build: Jekyll Build'
      run: JEKYLL_ENV=production bundle exec jekyll build --destination _site

    - name: 'Test: HTML Proofer'
      run: bash scripts/html_proofer.sh
      continue-on-error: true

    - name: 'Test: Rubocop'
      run: bundle exec rubocop

    - name: 'Test: Markdown Linter'
      run: bash scripts/markdown_linter.sh

    - name: 'Deploy: GitHub Pages Deploy'
      uses: emmasax4/github-pages-deploy-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: _site
        clean: true
        silent: true
        commit_message: "Deploy to ${{ github.repository }}"
        git_config_email: 41898282+github-actions[bot]@users.noreply.github.com
        git_config_name: github-actions[bot]

    - name: 'Notifications: Set Deploy Status Message'
      run: bash scripts/set_deploy_status_message.sh ${{ env.DEPLOYMENT_STATUS }}

    - name: 'Notifications: Notify Slack on Success'
      if: success()
      uses: emmasax4/slack-notifier-action@main
      with:
        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
        channel: "#general"
        icon_url: https://i.imgur.com/DGrghtn.png
        username: GitHub Actions
        color: "#23c22e"
        title: ${{ github.repository }}
        title_link: https://github.com/${{ github.repository }}
        author_name: ${{ github.actor }}
        author_icon: ${{ env.ACTOR_ICON }}
        text: >-
          Build <${{ env.BUILD_URL }}|${{ github.run_id }}> on branch `${{ env.BRANCH }}`
          *passed*. ${{ env.DEPLOY_MESSAGE }}.

    - name: 'Notifications: Notify Slack on Failure'
      if: failure()
      uses: emmasax4/slack-notifier-action@main
      with:
        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
        channel: "#general"
        icon_url: https://i.imgur.com/DGrghtn.png
        username: GitHub Actions
        color: "#bd2222"
        title: ${{ github.repository }}
        title_link: https://github.com/${{ github.repository }}
        author_name: ${{ github.actor }}
        author_icon: ${{ env.ACTOR_ICON }}
        text: >-
          Build <${{ env.BUILD_URL }}|${{ github.run_id }}> on branch `${{ env.BRANCH }}`
          *failed*. ${{ env.DEPLOY_MESSAGE }}.
