name: Develop
on:
  pull_request:
    branches: [ source ]

slack_info: &slack_info
  channel: '#general'
  icon_url: https://img.icons8.com/ios-filled/50/000000/github.png
  username: GitHub Actions
  title: ${{ github.repository }}
  title_link: https://github.com/${{ github.repository }}
  author_name: ${{ github.actor }}
  author_link: https://github.com/${{ github.actor }}
  author_icon: https://github.com/${{ github.actor }}.png

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Define Variables
      run: |
        pull_id=$(echo ${{ github.ref }} | sed -E 's|refs/pull/||' | sed -E 's|/merge||')
        echo "::set-env name=PULL_ID::$pull_id"
        echo "::set-env name=PULL_URL::$(echo https://github.com/${{ github.repository }}/pull/$pull_id)"
        echo "::set-env name=BRANCH::$(echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
        echo "::set-env name=BUILD_URL::$(echo https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"

    - name: Switch to Current Branch
      run: git checkout ${{ env.BRANCH }}

    - name: Configure Bundler
      run: sudo gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d ' ')

    - name: Configure Gem Cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundler-cache-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundler-cache-

    - name: Install Gems
      run: bundle config set path 'vendor/bundle' && bundle install

    - name: Jekyll Build
      run: JEKYLL_ENV=production bundle exec jekyll build --destination ./_site/

    - name: HTML Proofer
      run: bundle exec htmlproofer --assume-extension --allow-hash-href --internal-domains /emmasax4.info/ --only_4xx ./_site/

    - name: Set Slack Message
      run: |
        echo "::set-env name=MESSAGE::$(echo Build <${{ env.BUILD_URL }}|${{ github.run_id }}> on branch `${{ env.BRANCH }}` in PR <${{ env.PULL_URL }}|#${{ env.PULL_ID }}>)"

    - name: Notify Slack on Success
      if: success()
      uses: emma-sax4/action-slacker@emmasax4_action_slacker
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        <<: *slack_info
        color: '#23c22e'
        text: ${{ env.MESSAGE }} *passed*.

    - name: Notify Slack on Failure
      if: failure()
      uses: emma-sax4/action-slacker@emmasax4_action_slacker
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        <<: *slack_info
        color: '#bd2222'
        text: ${{ env.MESSAGE }} *failed*.
