name: Release
on:
  push:
    branches: [ source ]
  schedule:
    - cron: '30 5 * * 1' # On Mondays: 05:30 UTC => 00:30 CDT / 23:30 CST

jobs:
  build:
    name: Test and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Prepare Repository
      run: git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
    - name: Configure Bundler
      run: sudo gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d ' ')
    - name: Configure Gem Cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundler-cache-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundler-cache-
    - name: Install Dependencies
      run: .github/workflows/bundle-install.sh
    - name: Jekyll Build
      run: JEKYLL_ENV=production bundle exec jekyll build --destination ./_site/
    - name: HTML Proofer
      run: .github/workflows/html-proofer.sh
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: _site
        COMMIT_MESSAGE: 'Deploy to ${{ github.repository }}.git:master via GitHub Actions'
        CLEAN_EXCLUDE: '[".git", ".circleci", ".github"]'
    - name: Notify Slack on Success
      if: success()
      uses: emma-sax4/action-slacker@emmasax4_action_slacker
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        channel: '#general'
        icon_url: https://img.icons8.com/ios-filled/50/000000/github.png
        username: GitHub Actions
        color: '#17e625'
        title: ${{ github.repository }}
        title_link: https://github.com/${{ github.repository }}
        author_name: ${{ github.actor }}
        author_link: https://github.com/${{ github.actor }}
        author_icon: https://github.com/${{ github.actor }}.png
        text: 'Build #${{ github.run_id }} on `${{ github.ref }}` *passed*. Deploy to GitHub Pages was *successful*.'
        footer: 'Event: ${{ github.event_name }}'
    - name: Notify Slack on Failure
      if: failure()
      uses: emma-sax4/action-slacker@emmasax4_action_slacker
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        channel: '#general'
        icon_url: https://img.icons8.com/ios-filled/50/000000/github.png
        username: GitHub Actions
        color: '#d11515'
        title: ${{ github.repository }}
        title_link: https://github.com/${{ github.repository }}
        author_name: ${{ github.actor }}
        author_link: https://github.com/${{ github.actor }}
        author_icon: https://github.com/${{ github.actor }}.png
        text: 'Build #${{ github.run_id }} on `${{ github.ref }}` *failed*. Deploy to GitHub Pages was *skipped*.'
        footer: 'Event: ${{ github.event_name }}'
