name: Develop
on:
  pull_request:
    branches: [ source ]
  push:
    branches: [ source ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure Bundler
      run: sudo gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d ' ')
    - name: Configure Gem Cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundler-cache-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundler-cache-
    - name: Install Dependencies
      run: |
        bundle config set path 'vendor/bundle'
        bundle install
    - name: Jekyll Build
      run: JEKYLL_ENV=production bundle exec jekyll build --destination ./_site/
    - name: HTML Proofer
      run: |
        bundle exec htmlproofer \
          --assume-extension \
          --allow-hash-href \
          --internal-domains /emmasax4.info/ \
          --url-ignore /linkedin/,/digikey/,/maasaimara/ \
          --only_4xx \
          ./_site/
    - name: Notify Slack
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_CHANNEL: general
        SLACK_ICON: https://1000logos.net/github-logo/
        SLACK_MESSAGE: "$SLACK_MESSAGE *completed*."
        SLACK_USERNAME: GitHub Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
