name: Develop
on:
  pull_request:
    branches: [ source ]
  push:
    branches: [ source ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.5' # hard-code this from .ruby-version
    - name: Configure Bundler
      run: sudo gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d ' ')
    - name: Install Dependencies
      run: bundle install --path vendor/bundle
    # - name:
      # uses: meitar/jekyll-builder-for-github-pages-action@v1
      # with:
      #   who-to-greet: 'Mona the Octocat'
      # id: hello




    # - name: Configure Gem Cache
    #   uses: actions/cache@v1
    #   with:
    #     path: vendor/bundle
    #     key: bundler-cache-${{ hashFiles('**/Gemfile.lock') }}
    #     restore-keys: bundler-cache-
