name: Develop
on:
  pull_request:
    branches: [ source ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Prepare Repository
      run: git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
    - name: Configure Bundler
      run: sudo gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d ' ')
    - name: Configure Gem Cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundler-cache-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundler-cache-
    - name: Install Dependencies
      run: .github/workflows/bundle-install.sh
    - name: Jekyll Build
      run: JEKYLL_ENV=production bundle exec jekyll build --destination ./_site/
    - name: HTML Proofer
      run: .github/workflows/html-proofer.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Jekyll Site
        path: _site/
    - name: Notify Slack on Success
      if: success()
      uses: emma-sax4/action-slacker@emmasax4_action_slacker
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        channel: '#general'
        icon_url: https://img.icons8.com/ios-filled/50/000000/github.png
        username: GitHub Actions
        color: '#17e625'
        title: ${{ github.repository }}
        title_link: https://github.com/${{ github.repository }}
        author_name: ${{ github.actor }}
        author_link: https://github.com/${{ github.actor }}
        author_icon: https://github.com/${{ github.actor }}.png
        text: 'Build #${{ github.run_id }} on `${{ github.ref }}` *passed*.'
        footer: 'Event: ${{ github.event_name }}'
    - name: Notify Slack on Failure
      if: failure()
      uses: emma-sax4/action-slacker@emmasax4_action_slacker
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        channel: '#general'
        icon_url: https://img.icons8.com/ios-filled/50/000000/github.png
        username: GitHub Actions
        color: '#d11515'
        title: ${{ github.repository }}
        title_link: https://github.com/${{ github.repository }}
        author_name: ${{ github.actor }}
        author_link: https://github.com/${{ github.actor }}
        author_icon: https://github.com/${{ github.actor }}.png
        text: 'Build #${{ github.run_id }} on `${{ github.ref }}` *failed*.'
        footer: 'Event: ${{ github.event_name }}'
